### ISSUE TITLE
[Proposals] View the list of proposal in tabs

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#10]
As a LikeCoin community member, I want to check proposals we have, so that I can participate in the DAO operation

## Acceptance Criteria
- [x] Proposals are organized in 5 tabs: Voting, Deposit, Passed, Rejected, Following
- [x] When unconnected, there's no `Following` tab
- [x] Support pagination (Page size = 5)
- [x] Support RWD (the tabs will be a horizontal scroll container)
- [x] See voting results/progress bar to display the voting distribution
- [x] Following: the proposal that user has voted, deposited, or commented
  (the filter logic for comment can be done after comment feature built up)
- [ ] See people's reaction to the proposal, when clicking the emoji reaction, enter details page

## Test flow
1. Try login and not login
2. Check each tab and compare with https://stake.like.co/
3. Try voted on some proposals in https://stake.like.co/ and see the difference

## UI
https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=70%3A4471
![image.png](https://zube.io/files/oursky/31e105dc3829f64893c77e49cfdf1c2c-image.png)

## No need to include in this user story
1. Add reaction: we can integrate with fake data first
2. The filter of following tab: commented proposals, the filter logic for comment can be done after comment feature built up
3. Search bar

## Reference
[The status of proposals](https://docs.cosmos.network/master/modules/gov/02_state.html)
```
    StatusNil           ProposalStatus = 0x00
    StatusDepositPeriod ProposalStatus = 0x01  // Proposal is submitted. Participants can deposit on it but not vote
    StatusVotingPeriod  ProposalStatus = 0x02  // MinDeposit is reached, participants can vote
    StatusPassed        ProposalStatus = 0x03  // Proposal passed and successfully executed
    StatusRejected      ProposalStatus = 0x04  // Proposal has been rejected
    StatusFailed        ProposalStatus = 0x05  // Proposal passed but failed execution
```

**Comment by hochiw** [comment]
@chihimng do we use relay cursor based style for the pagination? do you know how does the query work for the db?

**Comment by rickmak** [comment]
I think relay cursor is good. Post the link here to make sure we are talking the same thing: https://relay.dev/graphql/connections.htm

The relay spec only talk about how to navigate front and back vis cursor, the content of the cursor will be an opaque string for the front end. It just pass to backend and interpret in their way.  The backend will return the content accordingly.

Being said that, I think to keep it simple. We will use pain old offset at psql level? Book keeping of psql cursor is huge work and not worth the effort for stateless web request.

**Comment by hochiw** [comment]
@mitchellchou @frank-oursky just checked the other designs and found out the validator list and active proposal list in portfolio screen is using page based pagination but the proposal list in overview is using one-way pagination where you get 5 new items everytime you click `View more proposals`. Which one shall we use for the proposal list in proposal screen?

**Comment by mitchellchou** [comment]
@Rico-Wong 
I think the behavior after clicking `View more proposals` is redirecting to proposal list page (not show more proposals in the overview page)
For proposal list page, let's use pagination

**Comment by hochiw** [comment]
oh okay

**Comment by hochiw** [comment]
Will handle reactions altogether in oursky/likedao#25

**Comment by mitchellchou** [comment]
## Description
1. Testnet "Rejected" tab and "Following" tab will turn to Unknown error page
2. Testnet "Passed" has no proposals
2. Mainnet proposals only have up to proposals 15, but we should have #48 proposals already

## Expected
1. Should see those tab and their proposals
2. Should have at least proposal 1 about chain upgrade 
2. Should see all proposals 

## Screenshot
![image.png](https://zube.io/files/oursky/5f295bf098d1328361234cf7dc8f73a8-image.png)
![image.png](https://zube.io/files/oursky/5ebca3b47091c8015dbdef3b86641b30-image.png)
![image.png](https://zube.io/files/oursky/a3a7fab0f7c1b96e07ffd914b409397f-image.png)


## Other info
1. Bigdipper returned error when I tried to visit proposals older than #15 
2. stake.like.co can still query all proposals

**Comment by hochiw** [comment]
Seems like the proposals are not synchronized properly...

**Comment by hochiw** [comment]
@mitchellchou If there are 0 votes for a rejected proposal what do we should the 'Most voted on' as? :sosad:

**Comment by hochiw** [comment]
And would the colour bar at the bottom look like the deposit one in the screenshot?
![Screenshot 2022-06-16 at 6.38.09 PM.png](https://zube.io/files/oursky/9b98a3484673158fbb814df40fdce6e7-screenshot-2022-06-16-at-6-38-09-pm.png)

**Comment by mitchellchou** [comment]
@hochiw 

> @mitchellchou If there are 0 votes for a rejected proposal what do we should the 'Most voted on' as? :sosad:

Let's align with how we handle deposit proposals == hide `Most voted on`
![image](https://user-images.githubusercontent.com/62210372/174071511-1335bdda-f027-4e42-bb34-8a1f7cc3c1df.png)


> And would the colour bar at the bottom look like the deposit one in the screenshot?

Yes, let's do this
