### ISSUE TITLE
[Validators] Your stake

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#103]
This is similar to oursky/likedao#112 

## Acceptance criteria
- [x] I can see my staked and rewards from this validator when I'm
  1. Connected & Staked in
  2. Already untaked but still have unclaimed rewards
- [x] I can't see this section(hide) when I'm 
  1. not connected
  2. not staked or have rewards in this validator

## Design
![image.png](https://zube.io/files/oursky/f970107cddc35ad41275c3f693048ba0-image.png)

**Comment by chihimng** [comment]
- RPC query for staked amount, pending rewards [2]
- get expected returns from gql response [0.5]
- UI [0.5]
