### ISSUE TITLE
[Validators] Proposal history

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#104]
## Acceptance criteria
- [ ] Please check oursky/likedao#109
- [ ] I can see the proposal participation history of this validator
- [ ] Support pagination (page size=2)

## Design
![image.png](https://zube.io/files/oursky/cfe83edd64c7bbab54bf71513982b961-image.png)

## Remarks 
- Search will be done later

**Comment by chihimng** [comment]
@mitchellchou what does the percentage bar represent?

**Comment by chihimng** [comment]
- backend: gql schema / query for voting history, data loader / db query for voting records by voter address, sorting, pagination [6]
- backend: gql schema / query for submitted proposal, data loader / db query for submitted proposals by address, sorting, pagination [6]
- backend: gql schema / query for deposited proposal, data loader / db query for deposited proposals by address, sorting, pagination [6]
- UI: filter tab, table x3 [6]
- UI: pagination, sorting x3 [3]

**Comment by mitchellchou** [comment]
> @mitchellchou what does the percentage bar represent?

Voted: The options ratio that I have voted
Submitted & Depositted: Hide this bar
![image](https://user-images.githubusercontent.com/62210372/174713848-ba1bd390-f153-4595-9a3e-0ebcd7363e4a.png)

**Comment by chihimng** [comment]
@ivanng-oursky plz open task issue for first api, and plan graphql / db query briefly before starting

**Comment by ivanng-oursky** [comment]
@chihimng seems keplr is using latest pool size to calculate turnout rate for all proposals?

turnout calculation
https://github.com/chainapsis/keplr-wallet/blob/7ca025d32db7873b7a870e69a4a42b525e379132/packages/stores/src/query/cosmos/governance/proposal.ts#L64-L70

bondedTokens getter
https://github.com/chainapsis/keplr-wallet/blob/7ca025d32db7873b7a870e69a4a42b525e379132/packages/stores/src/query/cosmos/staking/pool.ts#L29-L42

**Comment by ivanng-oursky** [comment]
@mitchellchou some links for testing

https://testnet.likedao-dev.pandawork.com/validators/likevaloper1hgwvq3txyfux7uhl44qxdtx9f2qplau30dgzru

https://testnet.likedao-dev.pandawork.com/validators/likevaloper1sxjgwl2m35c6sah4f3yhd764csn307als4pm02

https://testnet.likedao-dev.pandawork.com/validators/likevaloper10xnsuy5teht2snw45sgv9qjyda4fr3y5rafvkw

**Comment by mitchellchou** [comment]
will test with oursky/likedao#109
