### ISSUE TITLE
[Validators] Validators details

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#105]
## Acceptance criteria
- [x] I can see the validator's profile
- [x] I can see the Information section of this validator
- [x] I can click on this validator's address and switch to its wallet portfolio page

## Test flow
Check bigdipper

## Design
![image.png](https://zube.io/files/oursky/9e52a0f1d57eddca838981545d1a21b7-image.png)

## Remarks
- Let's make the value of validator since & Max commission rate & Last Commission change use black-font because it's unclickable but dark-green indicates clickable
![image.png](https://zube.io/files/oursky/5db3efb3388ba10f812129033c7bd010-image.png)
- Annual profit: "inflation / staking ratio * (1-commssion rate)" this is provided by Kin, but please consult Rick before you get started

**Comment by ivanng-oursky** [comment]
@mitchellchou are the annual profit (in first panel) and expected return (in your stake panel) actually referring to the same value? If not, what is the difference between them?

![image.png](https://zube.io/files/oursky/5a9c577853c59b5c2a60e4cdf293ae15-image.png)

![image.png](https://zube.io/files/oursky/197fe3c13f007a3d992359e5cae6e3df-image.png)

**Comment by mitchellchou** [comment]
@ivanng-oursky I think no. 
Annual profit is the profit this validator would make; Expected Returns is when you stake in this validator how much can possibly return

Please consult Rick on how annual profit is calculated.

**Comment by chihimng** [comment]
@mitchellchou so annual profit is what would be gained by the node operator? don't think that info is useful to most users? (and the label would be misleading - as user i would expect "Annual Profit" to mean what I would earn if i stake with that validator)

**Comment by mitchellchou** [comment]
The expected returns should come from current dao.like.co 
![image](https://user-images.githubusercontent.com/62210372/177953621-4329971f-d629-46b3-85d8-70cc74e60e72.png)

The annual profit should come from [ping.hub](https://ping.pub/likecoin/staking/likevaloper1e6448stejq3v86vypvxkz8jauqfdq24pngd0zs)
![image](https://user-images.githubusercontent.com/62210372/177953789-6b8b3ee5-1287-4dde-8671-cd370da248fb.png)

And based on this [article](https://matters.news/@daisy/234303-%E4%B8%80%E5%80%8B-ping-pub-%E7%9B%A1%E6%83%85%E7%AE%A1%E7%90%86-like-huahua-osmo-atom-bafyreih6272qbamc2245kwkzhylpsb4asdevdfheg6jup2wovartyt5fcu),  annual profit is what would be gained by the node operator

![image](https://user-images.githubusercontent.com/62210372/177954673-6569a96c-d04f-4785-83a4-5ea6a50c149d.png)

@chihimng I guess it might be a useful info because staking also allows validator to vote on my behalf, so I want to know how rich it is?

**Comment by chihimng** [comment]
i guess "Operator Annual Profit" would be better in this case?

**Comment by mitchellchou** [comment]
I think you are right, let's don't show the annual profit field for now. Thank Thank
as its name is not intuitive, and people usually tell if a validator is earning reasonable money by commission rate already. (I also asked Kenji and he thought it was the staking rewards)

**Comment by mitchellchou** [comment]
1. Let's drop "Desmos" for now. Only need to display info that we can query from likecoin chain (moniker I think?)
2. Rename the Annual profit to `APY` and shows the expected return when I stake to this validator
3. Remove the "Expected Returns" field from your stakes section (only remove for validator details page)

**Comment by mitchellchou** [comment]
https://mainnet.likedao-dev.pandawork.com/validators/likevaloper1knfp5qgzgr29k00nhjp2qzxlezrlalhyh77e4c

1. wrong self stake
2. wrong max commission / max daily commission

compare to 
1. https://stake.like.co/validators/likevaloper1knfp5qgzgr29k00nhjp2qzxlezrlalhyh77e4c
2. https://bigdipper.live/likecoin/validators/likevaloper1knfp5qgzgr29k00nhjp2qzxlezrlalhyh77e4c

![截圖 2022-07-21 下午7.43.51.png](https://zube.io/files/oursky/1b5bca8394e007c1c0d1eb82ec1e7663-2022-07-21-7-43-51.png)
![截圖 2022-07-21 下午7.38.20.png](https://zube.io/files/oursky/7d5c0d2b2521c8780d6a781a963706e2-2022-07-21-7-38-20.png)
