### ISSUE TITLE
[Validators] Stake, Unstake

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#106]
As a likecoin owner, I want to stake and unstake my LIKE to a validator, so that I can support this validator and earn rewards

## Acceptance criteria
- [x] When unconnected, I click and trigger connect to wallet
- [x] I can stake/unstake a validator, decide the amount and sign for it 
- [x] The `To`, `From` input is disabled in the modal
- [x] Click `max` and auto input my available LIKE amount

## Design
![image.png](https://zube.io/files/oursky/fb9c9da73ca63e71097ec35819a31f50-image.png)
![image.png](https://zube.io/files/oursky/7dc444de0b1418eb86b8243ddd21d4a1-image.png)

## Remarks
Let's ignore the success modal in the figma because we are using toast right now

**Comment by chihimng** [comment]
- Modal / logic for stake [3]
- Modal / logic for unstake: need to query existing stake [3]
