### ISSUE TITLE
[Portfolio] Your portfolio

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#108]
As a Likecoin wallet address owner, I want to see the details info about the history and current status of my wallet so that I can manage my account

## Acceptance Criteria
Positive
- [ ] I can see my portfolio
- [ ] I can see my desmos profile that connect to my wallet
- [ ] Guard the portfolio page when not connected to wallet, and will trigger connect to wallet modal

General
- [ ] Support RWD

## Content
- Name
- Wallet address (one-click copy)
- Total amount of LIKE I have (rounded off & actual)
- Stake: total amount I own
- Unstaking: the like in unbonding period
- Available: total - stake - unstaking

## Test flow
1. Try click and copy address
2. Compare to the data I see on bigdipper
3. Check my desmos page

## Design
[Figma](https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=117%3A2568)
![image.png](https://zube.io/files/oursky/d7ac30238d85c4c6d4c6ca0c4e9b673d-image.png)

## Reference
- Unstaking: https://www.forbole.com/blog/unbonding-period-in-cosmos-bpos-ch
- desmos profile:https://docs.desmos.network/next/
- Oursky's desmos profile: https://explorer.desmos.network/accounts/desmos1ze7n3xsfd7na2saj070v0cx0eu7twng9dxxrlt
- bigdipper is a block explorer that provides a website UI for non-tech users to view the chain data: https://likecoin.bigdipper.live/

**Comment by mitchellchou** [comment]
build: dev  

## Description
1. When unconnected,visiting portfolio page and see error msg
2. The portfolio data is different from [bigdipper](https://likecoin.bigdipper.live/accounts/like1yrzytk9urmdvn0rkpt6r0hjuhdpth547zypzfd) 

## Expected results
1. Should trigger connect to wallet modal when unconnected, instead of visiting portfolio page and see error msg
2. Available = 44, Unstaking = 8

## Screenshot
![截圖 2022-06-27 上午11.42.16.png](https://zube.io/files/oursky/801bf248a70f46b82a7689912a28227c-2022-06-27-11-42-16.png)
![image.png](https://zube.io/files/oursky/dfd49bebc3edbc6a6ceff5747ebad6ec-image.png)

**Comment by ivanng-oursky** [comment]
@mitchellchou incorrect balances are fixed in #183, I realised I made a few mistakes when working on that PR. 

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/106721852/175858014-94afa2f5-d0f2-41ce-8954-fe0fd7854b76.png">

I will open an issue to fix the open connect wallet dialog if not logged in. (sorry for not reading the requirements carefully, I will double check from now on)

**Comment by mitchellchou** [comment]
@ivanng-oursky The total LIKE didn't match

1. cosmos1yrzytk9urmdvn0rkpt6r0hjuhdpth5473caq2k
![image.png](https://zube.io/files/oursky/ac00c01d146d50003385bdb505b027db-image.png)

2. https://likecoin.bigdipper.live/accounts/cosmos1yrzytk9urmdvn0rkpt6r0hjuhdpth5473caq2k
![image.png](https://zube.io/files/oursky/22c331270b34ed2531e47fbd0db17337-image.png)

## Expected results
1. Okay that Reward shows 0 after rounding
2. The total should be `75.365` and `75.365243764 `

**Comment by ivanng-oursky** [comment]
Bigdipper seems to be having issue fetching the lastest data

<img width="593" alt="image" src="https://user-images.githubusercontent.com/106721852/178428300-83070c0f-05a4-4574-8e47-6effd4a49287.png">

@mitchellchou 
I have checked a couple addresses against https://likecoin-public-testnet-5.netlify.app/ and from direct rpc query, I think its safe to assume our balance values are correct. Most likely BigDipper's data was inaccurate or not yet updated.

cosmos1yrzytk9urmdvn0rkpt6r0hjuhdpth5473caq2k
| test site | lunie | rpc | 
| -------- | ----- | --- |
| <img width="683" alt="image" src="https://user-images.githubusercontent.com/106721852/178428969-c055da22-9c0b-4197-bfbe-e6fa7a836e9d.png"> | <img width="928" alt="image" src="https://user-images.githubusercontent.com/106721852/178429266-1d0e4b82-8f8c-4d9e-9073-0e04cb98f28b.png"> | <img width="192" alt="image" src="https://user-images.githubusercontent.com/106721852/178429383-342b079c-9a98-4260-bc58-72ebaf9a3ae7.png"> |

like1sxjgwl2m35c6sah4f3yhd764csn307alx6h9le
| test site | lunie | rpc | 
| -------- | ----- | --- |
| <img width="860" alt="image" src="https://user-images.githubusercontent.com/106721852/178429932-64916ddc-2205-4739-8964-d83c157e1131.png"> | <img width="967" alt="image" src="https://user-images.githubusercontent.com/106721852/178429983-810ddc7e-f14a-485a-acff-88ae5a3c173b.png"> | <img width="227" alt="image" src="https://user-images.githubusercontent.com/106721852/178430142-df5dad94-1dd9-4594-94bb-edeeb03a47bf.png"> |
