### ISSUE TITLE
[Portfolio] Proposal history

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#109]
As a dao participant, I want to know my participation history so that I can arrange my future decisions.

## Acceptance criteria
- [x] I can filter by my vote, deposit, and submit
- [ ] Sort by submit time of this proposal (Not the time that I voted)
- [ ] I can see how many comments I left under this proposal
- [ ] Comment count = 0, when I don't have any comments in it
- [x] Support pagination (page size = 2)

## Content
OPTION: 
- Submitted: When there's no vote by me (e.g. I didn't vote for this proposals, or it hasn't entered voting period), shoe a light gray `-` to represent it's "N/A"
- Deposited: use `DEPOSIT` instead and shows the amount that I deposited 
![image.png](https://zube.io/files/oursky/b7747313af01473d0a287f9808cb4e05-image.png)

The bar
1. Voted: The options ratio that I have voted
2. Submitted & Depositted: Hide this bar
![image.png](https://zube.io/files/oursky/8170e22fc87da0e9437e160db20c3767-image.png)

## State
- [x] Empty state: `No Proposals` (Let's use the current one for proposals list)
![image.png](https://zube.io/files/oursky/55e7a93caa772bea85cf4e9e8dba9a8b-image.png)

## Design
![image.png](https://zube.io/files/oursky/60f1bcdde6969d2f11a8bcc0a84ccfd0-image.png)

## Remarks
1. search will be done later
2. Comment feature will be done later

**Comment by chihimng** [comment]
This should reuse #104, just query with account address instead of validator address

**Comment by mitchellchou** [comment]
https://testnet.likedao-dev.pandawork.com/portfolio/like1lgdk4868np0zf8gmngs3s6fuey9tp7hhujlvy7

Forever loading when trying to visit a tab that is supposed to have items
![image.png](https://zube.io/files/oursky/29b465a17d063b6e7050984cfcd42506-image.png)


Before I have voted for any proposal, I can visit the null voted proposal tab; after I voted, I can't see the proposal history anymore
