### ISSUE TITLE
Setup deployment

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#11]
- Setup blackbox
- Setup helm chart
- Encrypt deployment values
- Setup Makefile with deploy commands
- Create README.md for deployment information

**Comment by hochiw** [comment]
@rickmak do we deploy to pandawork? may i have a namespace?

**Comment by hochiw** [comment]
@rickmak can also help to create cloud db for graphql server and bdjuno? `likedao-server` and `likedao-bdjuno`?

**Comment by chihimng** [comment]
how about same server different schema @.@

**Comment by rickmak** [comment]
Please take it as open source, so the blackbox should not in this repo. Deployment config should at other repo.

**Comment by hochiw** [comment]
I checked out another project for the separate repo deployment, it seems like they have setup a bot to update the submodule on that repo automatically which triggers the deployment? Otherwise in our case the parent repo's github action would need to notify the deployment repo's github action to trigger the workflow which requires the user to modify the workflow when it's adapted by another chain. If it is okay for the deployment repo name to be exposed I think it would be more simple to checkout the deployment repo from the source repo's workflow for the deployment values.

**Comment by rickmak** [comment]
Don't expose the deployment repos. We should write a simple bot or daily push on standup.
