### ISSUE TITLE
Create reaction list and reaction picker

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#116]
- Install https://github.com/charkour/react-reactions
- Add like reaction
- Create reaction list and reaction picker component

- Integrate list and picker to Proposal Detail and Proposal list

**Comment by hochiw** [comment]
@mitchellchou If seems like if we want to add the likecoin icon to the reaction picker we will need to use this type of picker
![image.png](https://zube.io/files/oursky/c8161c82be66014492e7293c3a8bc157-image.png)

In this case we will also have to provide a list of reactions for the users to select, any suggestion?

**Comment by hochiw** [comment]
@mitchellchou sure, do we need to go to details page to add reactions? I see no such button in the listing pages

**Comment by mitchellchou** [comment]
> @mitchellchou sure, do we need to go to details page to add reactions? I see no such button in the listing pages

Yes, only can add or edit reactions on the details page

**Comment by hochiw** [comment]
@mitchellchou oh so these are for display only?

![Screenshot 2022-06-20 at 2.56.34 PM.png](https://zube.io/files/oursky/cc6ec33fd76309f4249f50a5a8c035e1-screenshot-2022-06-20-at-2-56-34-pm.png)

**Comment by mitchellchou** [comment]
> @mitchellchou oh so these are for display only?
> 
> ![Screenshot 2022-06-20 at 2.56.34 PM.png](https://camo.githubusercontent.com/6f08c741415e329ec4d51ff816f7749021475b50f1ffd8fc746c58086c8031f7/68747470733a2f2f7a7562652e696f2f66696c65732f6f7572736b792f63633665633333666437363330396634323439663530613561386330333565312d73637265656e73686f742d323032322d30362d32302d61742d322d35362d33342d706d2e706e67)

listing page: display only, 
1. I think it would be weird if you can edit(cancel a reaction) but cannot add 
2. It would be also weird if you add reaction without reading the details 
3. So let's only allow add and edit or any interaction on the details page~
