### ISSUE TITLE
Fix list styles

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#136]
We have applied a `list-style: initial` to the tailwind base class which breaks some of the components that use `ul` or `ol` as the initial style for those tags are dots. Applying the style directly to the markdown editor, using the `@layer component` tag or using a modular css with the style applied via nested selectors don't seem to work. See if we want to dig deeper into finding ways to apply the style to the markdown editor or just add `list-none` to the lists we have used and call it a day.

**Comment by chihimng** [comment]
How about:
```
.w-md-editor-preview {
  ul,
  ol {
    list-style: initial !important;
  }
}
```

we can inject via project scss: https://github.com/oursky/allo/blob/dev/services/web/src/styles/components/_tiktok.scss

or via screen scss: https://github.com/oursky/project-house/blob/f09341c40cdb0b178d2ee3f18e7d4bf21d7228c7/web/src/components/PostList/AudioPreviewPlayer.module.scss#L22

---

overriding tailwind stuff / global behavior just for this single component seems a bad fix to me

**Comment by hochiw** [comment]
God
