### ISSUE TITLE
Move away from Create React App

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#143]
Move from CRA to parcel.js

**Comment by chihimng** [comment]
I've experimented with this but not sure if it's worth it; The built in optimizations breaks svgs and some of our global overrides in x.module.scss (tried to fix issues i could find, but i'm afraid there's more broken stuff...)

Anyways the working tree is here: https://github.com/chihimng/likedao/tree/143-parcel-migrate
(& i've yet to fix some linting bugs in import checks)

maybe we should try another alternative before committing to parcel?

cc @Rico-Wong

**Comment by hochiw** [comment]
yeah sure if the migration takes equal or more amount of effort than fixing bugs created by CRA then it's probably not worth it

**Comment by hochiw** [comment]
@chihimng Seems to have `Buffer is not defined` when adding reaction, F
