### ISSUE TITLE
[Overview] Recent proposals (Active proposals)

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#148]
As a member of likecoin community, I want to see the most recent proposals so that I can participate in governance.

## Remark
Let's make it `Recent Proposals` instead of active, as it is more often that there's no active proposal (confirmed by Kin)

## Acceptance criteria
Positive
- [x] Show the latest 4 proposals 
- [x] Sort by created time
- [x] Click view detail and redirect to proposal details page
- [x] Click view more and switch to proposal page 

Negative
- [x] No pagination needed
- [x] No empty state needed (only testnet could possibly be empty, let's do the easier one: "with empty state" or "without empty state"

## Design
![image.png](https://zube.io/files/oursky/7168cd0ad77959509888c18e10bc1133-image.png)

**Comment by ivanng-oursky** [comment]
related to oursky/likedao#10 
- UI: Create overview proposal panel [3]
  - data fetching: without filter, page size of 4 and sorted by date [1.5]
  - create panel by reusing proposal card component and integrate with API[1.5]

**Comment by mitchellchou** [comment]
@ivanng-oursky The title should be `Recent Proposals`
