### ISSUE TITLE
[Overview] Governance Info

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#150]
As a member of likecoin community, I want to know our governance params so that I can participate in dao and make correct judgement.

## Acceptance criteria
- [ ] I can see the current community gov params

## Test flow
1. Switch between testnet and mainnet
2. Compare the params with bigdipper 

## Design
![image.png](https://zube.io/files/oursky/1d33eadf859ddf8396321954f9464183-image.png)

## Ref
https://likecoin.bigdipper.live/params

**Comment by ivanng-oursky** [comment]
Data should be fetch from bdjuno `gov_param` table.

- Backend: Add graphql schema / query for gov params [3]
  - query: getGovParams
  - schema: `GovParams { ... }`
- UI: Create gov info card & add to overview screen [2]
