### ISSUE TITLE
[Doc] open source

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#160]

**Comment by mitchellchou** [comment]
open source license? GNU or NIT?

**Comment by rickmak** [comment]
Information supply:

tendermint and cosmos-sdk is Apache License V2. Likecoin-chain is GPL-3.0.

If we opt to GPL3, people can't take back our work as code in GPL3 can't switch back to ApacheV2.

**Comment by mitchellchou** [comment]
License: apache V2
