### ISSUE TITLE
[Reaction] Shouldn't be able to edit reaction after logout

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#202]
build: dev / testnet

## Description
1. I can still edit my reaction after logout
2. I can even edit my another account's reaction when I logout and login with another account

## Expected
Shouldn't be able to add/edit reaction after logout (probably need to also check if this user is logged in or not?)

## Screenshot
![image.png](https://zube.io/files/oursky/0b545e65b07d2ac4a68a104d060fcd89-image.png)

**Comment by hochiw** [comment]
hmm it's possible for the wallet session to expire but still authenticated on our site, especially for the case where the site tries to auto connect to wallet -> expired -> keplr asks user to connect -> user clicks cancel -> still authenticated

**Comment by mitchellchou** [comment]
Then I think we need to check if a user is connecting or not.
Can we delete the authentication in the browser when we found that we can fetch the authentication but the user is not connected? (just try to brainstorm, please don't mind me if there's better plan)

**Comment by hochiw** [comment]
The latest PR should be able to ensure the user is connected to a wallet before they could react, but we won't be able to tell if the wallet user is the same as the authenticated user. I think we will need to check and compare the wallet address to the authenticated address and revoke the token if they don't match

**Comment by hochiw** [comment]
@chihimng see if you think the following sounds sensible

Create `/auth/invalidate`  or `/auth/logout` to delete cookie

1. When user disconnects wallet manually, call logout API as well
2. When user wallet session expires automatically, clicking reaction will prompt the user to connect wallet, after connecting to wallet, call logout API
3. When user switch wallet account, call logout as well? (sounds chur tho)
