### ISSUE TITLE
[Reaction] reaction should be updated right when users edit it

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#224]
build: dev / testnet

## Description
The reaction wasn't updated until I reload the page

## Expected
reaction should be updated right when users edit it

## Screenshot

https://zube.io/files/oursky/d73906c4defd4a85f6496c200d440e83-2022-07-05-9-03-33.mov

**Comment by chihimng** [comment]
Should add optimistic ui, only revert after request fail
