### ISSUE TITLE
[Create Proposal] Walletconnect saw "User rejected call request" after approve

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#225]
build: dev / testnet

## Description
When I login with Walletconnect, I failed to submit the proposal and saw "User rejected call request" after click approve on my app

Same issue happened when I try to "vote" with walletconnect 

## Expected results
Should be able to submit proposal using walletconnect

## Screenshot
![截圖 2022-07-05 下午9.15.53.png](https://zube.io/files/oursky/77e12bca05926e9b42d7b9306b031e46-2022-07-05-9-15-53.png)

**Comment by hochiw** [comment]
timebox 2 hrs first

**Comment by hochiw** [comment]
@mitchellchou seems sending token is also not working now, do you remember if it worked before?

**Comment by mitchellchou** [comment]
@hochiw 
Yes, it worked when we first done the shortcut feature (we also recorded the demo video to the community)

**Comment by hochiw** [comment]
blocked, asked them in discord

**Comment by hochiw** [comment]
likerland has released a new version of the app and it seems to be working fine now.
