### ISSUE TITLE
[Proposals] Proposal detail

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#24]
As a dao participant, I want to check the details of a proposal, so that I can get the information that I want or decide to cast a vote.

## Acceptance Criteria
Positive 
- [ ] Click in a proposal, I can see the latest info of a proposal
- [ ] Click the "link" button, and copy the url of this proposal 
- [ ] Click the share button, and open the share sheet of mobile
- [ ] Display `Deposit period` when it's in the deposit stage & turn into `Voting period` after it enters voting stage.

Negative
- [ ] "Share" button only visible on mobiles (because we have no plan to integrate with social medias for now)
- [ ]  There will be no title for an account such like `community manager`
- [ ] Don't show "12 days left" when it's not in the deposit or voting stage

General
- [ ] Support RWD

## Content
- Proposal no.
- Proposal Title
- status: Voting / Passed / Rejected / Deposit
- Voting Period
- Deposit
- Turn out
- Proposal type
- Published by (contains: member name, wallet address)
- Start date
- Proposal body (will not only support text proposal in the future)

## UI
Figma: https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=96%3A3182
![image.png](https://zube.io/files/oursky/274ba8436de6de3b54dd46dd3f7bb0eb-image.png)

**Comment by mitchellchou** [comment]
@ivanng-oursky 
buiild: dev & testnet https://testnet.likedao-dev.pandawork.com/proposals/2

## Description
See "13 days left" on a rejected proposal

## Expected results
Should not have a badge "13 days left" when a proposal is not in voting or deposit period

## Screenshot
![image.png](https://zube.io/files/oursky/cda4b90ef466e204b198c161a1e7e860-image.png)

**Comment by hochiw** [comment]
@ivanng-oursky btw i think you mapped votingEndTime to votingStartTime

**Comment by mitchellchou** [comment]
build: dev

## Description
Saw `Failed to fetch proposal` when visiting a new created proposal: https://testnet.likedao-dev.pandawork.com/proposals/3

## Expected
1. Should be able to see the proposal details when the proposal is accepted on chain (transaction success)
2. If it's because we need some time to process the content in our database? please change the error msg to something like "This page is still being prepared, please check back later"

## Screenshot
![截圖 2022-06-30 下午12.03.29.png](https://zube.io/files/oursky/08c8f2c890ec993c7e06148c3134bc74-2022-06-30-12-03-29.png)
