### ISSUE TITLE
Alter the helm to make no replacement of static file

### ISSUE THREAD

**Issue by rickmak** [oursky/likedao#265]
We should able to replace it will all helm value pass in. It should be more natural for other users.

**Comment by hochiw** [comment]
@rickmak so the static files should have their corresponding config map yaml file? i.e `bdjuno.config.yaml`, `react-app.config.js.yaml` etc, with significant configs placed in `values.yaml` and substituted by helm on deploy?

**Comment by rickmak** [comment]
Yes.
