### ISSUE TITLE
Fix error on empty proposal proposer

### ISSUE THREAD

**Issue by ivanng-oursky** [oursky/likedao#269]
Some proposals create at genesis have no proposer, causing proposal detail page at `/proposals/:id` throw an error. 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/106721852/179138707-d3f8c2af-0c0a-4153-89df-9f121bc7312b.png">

**Comment by joyzoursky** [comment]
@ivanng-oursky is this issue about the "Failed to fetch data" error?

<img width="1515" alt="Screenshot 2022-07-15 at 10 35 41 AM" src="https://user-images.githubusercontent.com/12539486/179136135-34b3fcde-c460-45ac-8ed7-f3df704d3c89.png">

**Comment by ivanng-oursky** [comment]
> @ivanng-oursky is this issue about the "Failed to fetch data" error?
> 
> <img alt="Screenshot 2022-07-15 at 10 35 41 AM" width="1515" src="https://user-images.githubusercontent.com/12539486/179136135-34b3fcde-c460-45ac-8ed7-f3df704d3c89.png">

@joyzoursky I think not, this is caused by staging site not able to connect to the server. But I don't have access to the server deployment status, maybe @hochiw might be able to offer more insights to this?
