### ISSUE TITLE
[Proposals] Create proposals (Text proposal)

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#27]
As a non-tech user, I want to be able to create proposals via built-up user interface so that I can easily participate in the community.

- [x] Please try to raise a proposal and see if the initial deposit can be zero 
(In the [cosmos SDK doc](https://docs.cosmos.network/master/modules/gov/01_concepts.html#deposit), it seems that the deposit must be positive )

## Acceptance Criteria
- [ ] When unconnected, click `submit Proposal` button and trigger connect to wallet
- [ ] For now, only have one option for proposal type: `Signaling`
- [ ] Allow rich-text editor to edit their proposal description
- [ ] Disable Sumbit Proposal when requirement not fulfilled. (missing type, title etc)
- [ ] Disable inputs that are not number or dot in initial Deposit field
- [ ] Check the input each time I done editing (e.g. click in and click outside of the input)
- [ ] I can create proposal without innitial deposit

general 
- [ ] Support RWD

## Screen behaviors
- Proposal type as a dropdown menu
- Proposal title placeholder: `Title without containing proposal type`
~For Initial deposit, show current balance and minimal required deposit~
- Submit
  - open a modal with deposit amount (copy from last step)
  - Triggar Sign with Wallet after clicking next
  - Redirect to the detail page of the new proposal 

## Error state
Title
1. Content too long: `This field cannot contain more than xxx characters`
2. Emply: `This field cannot be null`

Description
1. Content too long: `This field cannot contain more than xxx characters`
2. Emply: `This field cannot be null`

Initial Deposit
1. Amount not enough/empty: no need, the initial deposit can be zero
3. Amount larger than the user have: `Your current balance is not enough`

## Types
    - Signaling
    - Parameter Change
    - Community Pool Spend
    - Upgrade
    - Cancel Upgrade

## UI
Figma: https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=70%3A2999
![image.png](https://zube.io/files/oursky/fe7affb802aec0c69e034bb30d6a64bb-image.png)

**Comment by hochiw** [comment]
@mitchellchou tried with liked cli, seems can submit proposal with 0 deposit

>  When unconnected, click New Proposal button and trigger connect to wallet

I think it would be more common to put this check on a button that induces chain actions rather than page navigation. i.e would be more sensible to trigger wallet connection when the user clicks `submit proposal`?

>  For now, only have one option for proposal type: Signaling

Are `signaling` proposals just text proposals?

**Comment by mitchellchou** [comment]
Note: We found that a md editor would be easier and safer to handle, and we are planning to use this https://uiw.gitee.io/react-md-editor/

**Comment by mitchellchou** [comment]
@rickmak Is it okay that I try to submit a proposal on testnet? Should we inform community before that?
![image.png](https://zube.io/files/oursky/233b129133e1ff6bb8bca3461b580873-image.png)

**Comment by rickmak** [comment]
You can try, no need to inform before. Just state in the proposal, it is for testing.

**Comment by mitchellchou** [comment]
@Rico-Wong 

## Description
1. Sign failed when I have too much content in the description
2. The md editor can't preview bullet points and numbered list (But I can see them on bigdipper)

## Expected
1. Should have error msg when my input is too long 
2. Saw the sample on https://uiw.gitee.io/react-md-editor/ can preview bullet point, we should be able to make it, too?

## Screenshot
![截圖 2022-06-10 下午12.11.59 1（2）.png](https://zube.io/files/oursky/711932f486e54ad752c6694b6f32e333-2022-06-10-12-11-59-12.png)

**Comment by hochiw** [comment]
@mitchellchou seems the limit is changed from 5000 to 10000 for sdk 0.45+, let's revert it back to 5000 first and open an issue to set it back to 10000 when we upgrade to 0.46.

Will check the md editor config

**Comment by mitchellchou** [comment]
Can't preview the numbered list 

![image.png](https://zube.io/files/oursky/78bbfbd8ee0d3a49f7aacbfa3074ea25-image.png)
