### ISSUE TITLE
[Proposals] Vote/deposit

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#28]
As a dao participants, I want to vote or deposit for the proposal I care about, so that I can participate in the community governance.

## Acceptance criteria
Positive
- [x] I can vote for a proposal when connected 
- [x] When unconnected, click `Vote now` and trigger connect to wallet
- [x] When it's in the deposit stage, show `Deposit` instead of `Vote now`
- [x] If I vote for a proposal for more than once, the last vote choice will be counted.
- [x] Deposit modal > I can click "Max" to set a maximum value(my balance)

Negative
- [x] When it's an inactive proposal, hide the vote/deposit button

General
- [x] Support RWD

## Screen behavior
1. Click the Vote Now button 
2. Show Vote Modal with options in the modal
  - Yes 
  - No
  - NoWithVeto
  - Abstain
3. Sign and pay the gas fee / deposit 

## UI
Figma: https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=301%3A4971
![image.png](https://zube.io/files/oursky/225ea750693e442bb1a0de0caf2d1559-image.png)
![image.png](https://zube.io/files/oursky/7b507a8f10c741ba61640e8b5c115499-image.png)

**Comment by mitchellchou** [comment]
@Rico-Wong Let's hide vote / deposit button on the proposal details page when it's not in voting/deposit period
![image.png](https://zube.io/files/oursky/5b3ce98ded405311e2e1726765feee3a-image.png)

**Comment by hochiw** [comment]
> @Rico-Wong Let's hide vote / deposit button on the proposal details page when it's not in voting/deposit period ![image.png](https://camo.githubusercontent.com/0ab9f99863e73128dec7d6785bf8ddd291296c5ad9da9d0b554247b38756bf24/68747470733a2f2f7a7562652e696f2f66696c65732f6f7572736b792f35623363653938646564343035333131653265313732363736356665656533612d696d6167652e706e67)

Yes I handled this in the pr

**Comment by mitchellchou** [comment]
build: dev / testnet

## Description
Failed before the sign modal (saw transaction failed) "Error signing send token tx Error: Insufficient funds" when deposit

## Expected
Should be able to sign and deposit


## Screenshot
![截圖 2022-07-05 下午8.48.11.png](https://zube.io/files/oursky/a6bd284b00a948b398fc5a5d142b82b3-2022-07-05-8-48-11.png)
