### ISSUE TITLE
[Proposal details] Wrong number in the x days left

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#286]
https://testnet.likedao-dev.pandawork.com/proposals/14
![image.png](https://zube.io/files/oursky/026bf0fb26bbb12518e704d0b282db8c-image.png)

## Expected result
1. Shouldn't have this badge as the proposal is rejected already
2. should notice that the voting period and deposit period is not a fixed value between chains

**Comment by joyzoursky** [comment]
More cases and info supplemented in #307

**Comment by mitchellchou** [comment]
The badge was not shown in the voting period (no show in any period in think) 
![image.png](https://zube.io/files/oursky/4b92609268a8970d55d215718a1b7bb5-image.png)


This is not urgent, hiding is better than showing wrong numbers.
