### ISSUE TITLE
[Proposal] Transaction success but proposal fails to create when user deposit with MAX amount

### ISSUE THREAD

**Issue by joyzoursky** [oursky/likedao#306]
## Background
- Testing browser: Chrome on Mac
- Testing environment: testnet

## Description
If the user create a proposal and deposit MAX amount of coin, then after deducting the gas fee, it seems to have not enough amount as the user input value for initial deposit, and cannot create the proposal even though the transaction is successful.

## Steps to reproduce
1. Connect to wallet with an account with some EKIL
2. Go to Proposals
3. Create proposal
4. Click `~MAX` for initial deposit amount
5. Click Next, and Approve the gas fee (average)
6. See "Transaction broadcasted" but cannot find the submitted proposal on the board

## Expected result
Not so sure what is expected.
1. If there is a MAX button, it should be used for calculating the total cost for the whole transaction (including / deducting fee), otherwise user can never use it successfully.
2. Should / Can the transaction be blocked if the remaining amount is not enough for the initial deposit value, after deducting the gas fee?
3. If the proposal fails to create, is there any notification for user? Otherwise user is confused why it is not appearing.

## Video

https://user-images.githubusercontent.com/12539486/180211477-dec2d0bd-2e68-4fa8-a4ce-93e662e00fc5.mov

**Comment by hochiw** [comment]
> If there is a MAX button, it should be used for calculating the total cost for the whole transaction (including / deducting fee), otherwise user can never use it successfully.
> Should / Can the transaction be blocked if the remaining amount is not enough for the initial deposit value, after deducting the gas fee?

@mitchellchou I think either way we probably need to tell the user how much fee is deducted, whether it's from the amount or from the wallet. Let's pick one approach and align all the other modals

> If the proposal fails to create, is there any notification for user

There would be a toast if the transaction fails to deliver response, but apparently it deliver an error

**Comment by mitchellchou** [comment]
Let's remove "MAX"
