### ISSUE TITLE
[Proposal, Reaction] Self-selected emoji cannot be recognized after refreshing on another page

### ISSUE THREAD

**Issue by joyzoursky** [oursky/likedao#308]
## Background
- Testing browser: Chrome on Mac
- Testing environment: testnet

## Description
After approving for giving a reaction to proposal, then go to another page (or switch between Votes and Deposits tabs), then refresh and come again, the originally selected emoji does not show as selected state.

If user updates the emoji in this state, the final result is correct after leaving the proposal detail, but when updating the reaction the UI acts like selecting for another user.

If refresh directly on the same page it can reserve the state correctly, it only happens after switching to another page.

## Steps to reproduce
1. Go to a proposal detail page
2. Add a reaction to a proposal
3. Go to another page (e.g. proposals listing / switch to deposits from votes tab)
4. Refresh the page
5. Go to the same proposal detail page
6. See the added reaction is not in selected state for the same user
7. If user clicks the same or add another reaction, it will add to the original one or add another one, but not removing the original one (as being added by another user)

## Expected result
Should recognize the user selected emoji and display correctly on proposal detail page.

## Video
1.

https://user-images.githubusercontent.com/12539486/180225638-7cbdb5de-a72f-41e9-b00a-51d966ccd4f9.mov

2. 

https://user-images.githubusercontent.com/12539486/180225706-b8e02e85-87a5-47cc-879f-529afd7b6560.mov

**Comment by hochiw** [comment]
This is because we logout the user after auto-wallet connection to cater the fact that user can be auto-connected to a different account. Let's create a separate API to handle cookie validation
