### ISSUE TITLE
Create dummy  overview page with empty side bar

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#33]
- Create dummy overview page for demonstration as well as to make it easier to dev in the future
- Right hand side should only have the title of the current page 
- Sidebar should only have logo
- Handle hamburger menu on mobile

![Screenshot 2022-05-16 at 2.13.40 PM.png](https://zube.io/files/oursky/f7c7f5ab668bb8ca0646cdc7d2f98f3a-screenshot-2022-05-16-at-2-13-40-pm.png)

**Comment by mitchellchou** [comment]
build: https://mainnet.likedao-dev.pandawork.com/
device: macbook / chrome / dell monitor

## Description
The content center align when the screen size is wider

## Expected result
shouldn't the sidebar always in the left side of the page?

@frank-oursky could you advise 


## Screenshot
![image.png](https://zube.io/files/oursky/a2d65e55c6ed6e12a1a7b87679911173-image.png)

## Reference
I think this is discussed on Figma
![image.png](https://zube.io/files/oursky/ff244173030fe70df49c510b2ca61681-image.png)
stake.like.co
![image.png](https://zube.io/files/oursky/a5dd91e32e66277bc9f306260cd93f45-image.png)

**Comment by koskosm** [comment]
@mitchellchou yes I think it is what we have discussed in figma. Fixed sticky left navigation bar is not good to use in ultra wide screen.

**Comment by koskosm** [comment]
In short it is correct currently.
