### ISSUE TITLE
[Transactions] Error message when not enough gas fee

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#330]
Can we add a subtitle on the transaction fail toast when you're balance is not enough for the gas fee?

```
Transaction failed
Insufficient available balance for transaction fee
```

![截圖 2022-07-27 11.13.52.png](https://zube.io/files/oursky/78f383d1f59ef098b93548484b4f1c04-2022-07-27-11-13-52.png)

**Comment by hochiw** [comment]
@mitchellchou seems there's no specific error code for every error, unless we want to extract text from error logs for each error, would we just show the raw log? 

in this case it's something like 
```
"failed to execute message; message index: 0: 1010572681125nanoekil is smaller than 1010572806280nanoekil: insufficient funds"
```

**Comment by mitchellchou** [comment]
@Rico-Wong 

Can we have a prefix `System message:` or `System log:` before the raw log?

```
Transaction failed
System message:"failed to execute message; message index: 0: 1010572681125nanoekil is smaller than 1010572806280nanoekil: insufficient funds"
```

**Comment by hochiw** [comment]
yes
