### ISSUE TITLE
Review updated bdjuno build for likecoin

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#34]
Currently the bdjuno team is working on the likecoin dual prefix update, our repo is pointing to the latest commit of the said [branch](https://github.com/forbole/bdjuno/tree/aaron/likecoin_dual_prefix). While it successfully parses block information, there are some notable errors that occur from time to time in which the `staking_pool` table is not being updated. When the updated bdjuno build is officially released some time in the future, we should

1. Review the build and see if the said errors still occur
2. Update the submodule and point to the build

**Comment by mitchellchou** [comment]
need to wait until they release

**Comment by hochiw** [comment]
seems updated 
https://github.com/forbole/bdjuno/commits/chains/likecoin/mainnet

**Comment by hochiw** [comment]
not sure if I understand it correctly but seems like they have assumed all genesis validators have the `like1` prefix https://github.com/forbole/bdjuno/blob/c87cfab4ded132fd577f36242caa1e91b7046d90/modules/staking/utils_gentx.go#L31-L36

This will probably break some of the validator information

**Comment by hochiw** [comment]
And apparently the ordering of the supported prefix in the config also affects the outcome lol if I put `cosmos` before `like` it breaks
