### ISSUE TITLE
[Proposal] Proposal list does not auto refresh after user submitted a proposal

### ISSUE THREAD

**Issue by joyzoursky** [oursky/likedao#346]
_(Sync from GitLab issue tracker)_

## Background:
- Device / Browser (OS version): Macbookpro M1, Brave 1.41.100, macOS Bigsur 11.4
- Build: testnet(staging)

## Description:
After a user submits a proposal, the proposal list does not auto-refresh

## Steps to reproduce:
1. Open the site and log in using a wallet
2. Create a proposal
3. Type some text and submit the proposal
4. See the list does not update itself and the new proposal is not shown in the list unless user refresh manually

## Expected result:
Should update the proposal list automatically after a user submitted a proposal

## Screenshot:

https://user-images.githubusercontent.com/12539486/181575924-e4897628-979e-4ba5-8fab-a6ff24732370.mov

**Comment by mitchellchou** [comment]
The proposal need time to parse, can't fix

**Comment by joyzoursky** [comment]
it works well now, maybe just some slow loading causing it looks not auto changing
