### ISSUE TITLE
[Sidebar] Switch between testnet & mainnet

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#5]
As a chain user, I want to switch between testnet & mainnet so that I can view the data in different chain environment.

## Acceptance Criteria

Positive criteria

- [x]  User can select the current chain s/he is viewing
- [ ]  When deploying a new net (e.g. testnet-5), there is a way for developers or others to integrate the new net to our site
- [ ]  Support RWD

Negative criteria

- [ ]  When viewing one chain I won’t see another chain’s data (e.g. due to cache)

## Test flow

1. Switch and see the URL change
2. Check if the data is different from another net
3. Keep switching between chains and see if this causes any error.

## UI
![image.png](https://zube.io/files/oursky/5b3be7fb9ac2f9f047900d0cc48906b4-image.png)
![image.png](https://zube.io/files/oursky/daaca1f3472226c08aea8bf5dd052c2a-image.png)

**Comment by mitchellchou** [comment]
@Rico-Wong @rickmak 

Want to make this upcoming feature will allow users to switch between testnet & mainnet 
1. in the same env (i.e. production or at least not staging)
2. We redirect user to staging website when they switch to testnet

I think 1 is more ideal but if 2 is the case, are we going to use the pandawork domain?

**Comment by rickmak** [comment]
Good question, I think we did not consider multi-env in current planing, which will lead to multiple deployment for multiple env. In backend, it will be more resource consuming, but I think it's fine for now.


As for end user, like @mitchellchou, 1 & 2 might be different, but it is actually same for dev. It just about same domain or not.

For 1, I believe you refer to how [pin](https://ping.pub/) is doing.
For 2, I believe you refer to how BigDipper doing: https://likecoin.bigdipper.live/

For deployment, the different is just using path for routing or domain for routing. Which I will insist our program can support both @hochiw .

**Comment by mitchellchou** [comment]
standup note: will have 3 env
  - dev for internal (PM & QA) (pandaworks)
  - stg for community demo (users can switch between testnet & mainnet) (ourskydev)
  - prod (users can switch between testnet & mainnet)

**Comment by chihimng** [comment]
@mitchellchou i think dev for nightly, staging for qa and prod for demo / actual use

qa probably wants relatively stable build for testing, shouldn't use nightly builds

**Comment by mitchellchou** [comment]
@chihimng Then, how about?
1. dev for internal (PM & developers)
2. stg for QA and demo
3. Prod for actual use

I think demo should stay on stg, so that we can still have rounds of updates and demo (allow community to play around) after we first rollout the production site and somebody is really actively using?

**Comment by hochiw** [comment]
@rickmak do we use the same dbs for mainnet and testnet under the same env?

**Comment by mitchellchou** [comment]
use different dbs

**Comment by hochiw** [comment]
@rickmak can you create another set of dbs for mainnet in dev? :adore2x:

**Comment by rickmak** [comment]
Created, send via other channel.

**Comment by hochiw** [comment]
@mitchellchou if we were to do polling (automatic update) for this component as well as the community status, how long do you think the interval should be?

**Comment by rickmak** [comment]
@hochiw if you are referring to pooling of the block info. Let's do half of the block time, i.e. 3s by default.
