### ISSUE TITLE
[Footer] Link to Get token and help

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#6]
## Background

- This is copied from [ISCN app page](https://app.like.co/)

## Acceptance Criteria

- [ ]  Users can tap the button and open new tab that links to
    - [ ]  Osmosis: [https://app.osmosis.zone/?from=UST&to=LIKE](https://app.osmosis.zone/?from=UST&to=LIKE)
    - [ ]  Liquid: [https://app.liquid.com/exchange/LIKEUSDT](https://app.liquid.com/exchange/LIKEUSDT)
    - [ ]  Emeris: [https://app.emeris.com/welcome](https://app.emeris.com/welcome)
    - [ ]  Contact Support: [https://go.crisp.chat/chat/embed/?website_id=5c009125-5863-4059-ba65-43f177ca33f7](https://go.crisp.chat/chat/embed/?website_id=5c009125-5863-4059-ba65-43f177ca33f7)
- [ ]  Support RWD

## UI

Figma: [https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=69%3A1031](https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=69%3A1031)

![image.png](https://zube.io/files/oursky/80b9ece86d0e0cb087bbb8306b2018d6-image.png)

**Comment by chihimng** [comment]
@mitchellchou ust is dead (rip), let's use atom to like in osmosis url (seems iscn app updated as well)

cc @ivanng-oursky @hochiw
