### ISSUE TITLE
[Header] View Community status

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#7]
As a chain user, I want to know the current status of chain so that I can participate in the community.

## Acceptance Criteria
Positive
- [ ]  See the data of
    - [ ]  Community Pool
    - [ ]  Bonded Ratio
    - [ ]  inflation
- [ ]  See different layout on different pages (e.g. on proposal page, the status is not shown as cards)
- [ ]  Support RWD in overview page

Negative 
- [ ] no RWD version on pages other than overview

## Test flow
- Try different page width
- Try different page
- Try to reload the page
- Try to do some transaction

## Ui
https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=69%3A1031
1. Overview page
![image.png](https://zube.io/files/oursky/9bd1fa4275e811da92b5c01d60d24fb7-image.png)
2. Other pages
![image.png](https://zube.io/files/oursky/1a3abfd4de73d70d8dc4cd0e07ee3798-image.png)
3. RWD on overview page
![image.png](https://zube.io/files/oursky/4ce07a12d13a230bedc153471d4aa359-image.png)

**Comment by mitchellchou** [comment]
build: dev
device: chrome / mac

## Description
1. The dot always red in testnet
2. The community status returns "Internal Server Error" in mainnet

## Expected
1. The small dot should turn green when it's ready
2. Should return community status of mainnet

## Screenshot
![image.png](https://zube.io/files/oursky/8d13be3e2085865dc1bf8449578776df-image.png)
![image.png](https://zube.io/files/oursky/21e7b8e02d297f8a271db55d55033263-image.png)

**Comment by hochiw** [comment]
@mitchellchou bdjuno for mainnet seems to be up and running now, we will need a day for the data to get onto the db (since inflation is daily update) so maybe we check tmr

**Comment by hochiw** [comment]
seems ok now
