### ISSUE TITLE
[Sidebar] Connect to wallet

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#8]
As a LikeCoin user, I want to login with my wallet so that I can view my data or interact with chain

## Acceptance Criteria

- [x]  Open a modal for user to choose their login methods
- [x]  Users can use WalletConnect and their [Liker.Land](http://Liker.Land) wallet to login
- [x]  User can use Keplr extension to login
- [x]  User can access the website without login
- [x]  Support RWD (but may not be able to connect through mobile)
- [ ] Handle exceptions when using mobile and can't connect to wallet
- [x] Able to logout when click the exit icon 
![image.png](https://zube.io/files/oursky/4d832a5779dc11efa4c79ec8574f7c1e-image.png)

## Test Flow
- Try login with liker.land
- Try login with Keplr
- Try login with other chain’s wallet
- Try login with mobile view
- Try logout

## UI
Figma: https://www.figma.com/file/SMaKDFUALEopfVeDHcBemr/DAO-likecoin?node-id=70%3A3385
![image.png](https://zube.io/files/oursky/092db3843cbc0bb5cb68cd54dedb5cb5-image.png)
![image.png](https://zube.io/files/oursky/ec589141564b003c206dcf753ad827d1-image.png)
![image.png](https://zube.io/files/oursky/2b2f678f4a05e99feaef0277a89805d4-image.png)

**Comment by hochiw** [comment]
> Handle exceptions when using mobile and can't connect to wallet
> Try login with other chain’s wallet

@mitchellchou do we expect error from third-party wallets and mobile wallets? if so do we display it to user or just digest it silently? cc @frank-oursky

**Comment by mitchellchou** [comment]
@hochiw I think we should digest it and display the related error msg of our own

**Comment by hochiw** [comment]
> @hochiw I think we should digest it and display the related error msg of our own

@mitchellchou then i think we might need a design for displaying them with toast or modal? cc @koskosm

**Comment by chihimng** [comment]
i think we need a toast / non blocking message box anyways, for showing txn progress?

**Comment by mitchellchou** [comment]
Can use WalletConnect (amazing!!!)

build: dev
device: mac 12.1 / chrome

## Description
Prompt error "Failed to connect to wallet" when choosing to connect with Keplr Wallet

## Expected results
Should be able to connect with Keplr Wallet


## Screenshot
![image.png](https://zube.io/files/oursky/039b5e35d0e9b240b25aa3e8a5a70371-image.png)

**Comment by hochiw** [comment]
@mitchellchou oops seems i've missed a few lines for the deployment, redeployed, please try again 🙏
