### ISSUE TITLE
[Sidebar] Use shortcuts for connected wallet

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#9]
As a login user, I want to have some handy common functions, so that I can arrange my account faster

## Acceptance Criteria

- [x]  Only connected users see these
- [x]  User can see wallet info about:
    - [x]  Wallet Address (click & copy)
    - [x]  LikeCoin Balance (rounded off & actual)

Shortcuts 

- [x]  Send: User can open a modal and send their likecoin to others
- [x]  Receive: User can open a modal and share their wallet address with others
- [x]  Rewards: User can open a modal and claim the current rewards from all validators
- [x]  For RWD, shortcuts in the Burger Menu

Will handle this in later sprints
- [ ]  Reinvest: User can open a modal to Claim rewards from all validators (let's say Alice, Bob, Carol) and delegate the rewards back to Alice, Bob and Carol respectively.

## Test flow
1. When not connected, don't see shortcuts
2. Try each button(Send, Receive, Rewards, Reinvest)
3. For Rewards and reinvest, login to https://stake.like.co/ and stake to some validators before trying
4. Use bigdipper(https://likecoin.bigdipper.live/) to check the transaction results

## UI
![image.png](https://zube.io/files/oursky/09deeb9dbc177ee51481dfd797325000-image.png)
![image.png](https://zube.io/files/oursky/b1561dec49602510c2c6029fdcb8c4ae-image.png)
![image.png](https://zube.io/files/oursky/5b278f92a5164d04a329e0d863cd35b7-image.png)

**Comment by hochiw** [comment]
Will estimate this after oursky/likedao#8

**Comment by hochiw** [comment]
@mitchellchou 
seems like we won't be able to specify the amount of rewards the user is going to claim like the modal in the design, as there is no amount input for the request message

https://buf.build/cosmos/cosmos-sdk/docs/main:cosmos.distribution.v1beta1#cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward

**Comment by mitchellchou** [comment]
@Rico-Wong I just checked stake.like.co and this API returns how much rewards I can claim. Is this something that we can use?

https://mainnet-node.like.co/cosmos/distribution/v1beta1/delegators/cosmos1qmcz6k4tyzefz97cck8krauyewuruqvpuspaug/rewards


![image.png](https://zube.io/files/oursky/176bc7bae4d011c50243c390fabcef2d-image.png)

**Comment by hochiw** [comment]
@mitchellchou oh I misunderstood the component :sosad: thought it was an input field where you could type how much you want claim, nevermind then

**Comment by mitchellchou** [comment]
@Rico-Wong Can we hide `Reinvest` button until we have this feature?

**Comment by hochiw** [comment]
sure

**Comment by hochiw** [comment]
Let's handle with feature flag?

**Comment by mitchellchou** [comment]
@hochiw We don't have to often turn on/off the feature in the future just want to hide the button before it has function when showing to the community, would it make sense if we just "comment" it?
![image](https://user-images.githubusercontent.com/62210372/172775336-361b0881-45b3-4c17-9da9-3b24d3d40215.png)

But please follow the best practice 🙏

**Comment by rickmak** [comment]
Feature flag is always better than comment.
