### ISSUE TITLE
Keep authenticate session when connect to wallet

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#95]
TBC

**Comment by chihimng** [comment]
message content ref: https://eips.ethereum.org/EIPS/eip-4361

signing ref: https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-036-arbitrary-signature.md

keplr api: https://github.com/chainapsis/keplr-wallet/blob/master/docs/api/README.md#request-signature-for-arbitrary-message

**Comment by mitchellchou** [comment]
@rickmak Please review~

**Comment by rickmak** [comment]
i.e. If we have `DELETE /auth`, for logout all existing session. Then we need an redis or equivalent store.

**Comment by hochiw** [comment]
So server encrypt a key + expiry date as API key for the client to store as cookie, decrypt and validate next time they send it back? how about the nonce?

**Comment by hochiw** [comment]
But I guess this doesn't cater this part of the spec? if there is no datastore to identify duplication. Unless we just make it simpler and ignore this part 
https://eips.ethereum.org/EIPS/eip-4361

> A nonce should be selected per session initiation with enough entropy to prevent replay attacks, a man-in-the-middle attack in which an attacker is able to capture the user’s signature and resend it to establish a new session for themselves.

**Comment by hochiw** [comment]
@rickmak @chihimng updated flow, see if I have missed or misunderstood anything?

1. Client call GET `/auth/nonce` to get nonce generated by server
2. Set nonce to cookie
3. Client create payload with the nonce
4. User signs payload
5. Client sends the signed payload via POST `/auth/verify`
6. Client deletes nonce from cookie
7. Server verifies signature and messasge.nonce === cookie.nonce
8. Server signs payload + expiry date and return to client
9. Client set response as cookie

10. Client sends request with cookie
11. Server verifies signature

**Comment by chihimng** [comment]
for cookie signing, i suppose we can sign with hmac-sha256, ref: https://github.com/oursky/project-house/blob/a7d031306fe25702226c366eed7de724ddf57ba0/server/pkg/util/hmacsha256/hmacsha256.go

& set a cookie entry with `.sig` suffix?

alternatively we can use jwt, but less human readable

**Comment by chihimng** [comment]
& for the "api token" before, now we can just set the wallet address & auth expiry date at signed cookie; if verified valid we can set the user info for use at gql resolver context

**Comment by rickmak** [comment]
> 6. Client deletes nonce from cookie

It should be the server delete nonce. And it happen on 8, on return.

Hmm, I think you should separate what by browser, client code (js?), and server (via HTTP header). After separate those, I think it will be more clear to you.

**Comment by rickmak** [comment]
For cookie signing format, I think hmac-sha256 is common pick nowadays. Remember to put issue time as clear text for debug, also set the expiry of cookie correctly.

**Comment by hochiw** [comment]
note

https://github.com/cosmos/cosmjs/issues/844
